printWidth: 100
useTabs: true
tabWidth: 2
semi: false
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
