name: taskeee-deploy

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzru --delete
          path: ./
          remote_path: ~/Taskeee
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
          remote_port: ${{ secrets.PORT }}

      - name: copy files and run docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cp ~/envs/deploy.env ~/Taskeee/.deploy/.env
            cp ~/envs/backend.env ~/Taskeee/backend/.env
            cp ~/envs/frontend.env ~/Taskeee/frontend/.env
            cd ~/Taskeee/.deploy
            docker compose up -d --build
